language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - npm install -g coveralls@2
script:
  - yarn run test:single
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
