language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - yarn
script:
  - yarn test
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
