language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
script:
  - yarn test
  - yarn build
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
